# See http://goreleaser.com about this file
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/binq-gh/main.go
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archives:
- format: zip
  files:
    - nothing-to-bundle*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
- tap:
    owner: progrhyme
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  homepage: https://github.com/binqry/binq-gh
  description: Wrapper CLI for binq with GitHub features
  test: |
    system "#{bin}/binq-gh", '--version'
